get it the old way first

diff --git a/triggerAnotherTekton/task.yaml b/triggerAnotherTekton/task.yaml
--- a/triggerAnotherTekton/task.yaml
+++ b/triggerAnotherTekton/task.yaml
@@ -65,6 +65,28 @@ spec:
           echo "BUILD_NUMBER is ${BUILD_NUMBER}"
           echo "RUN_ID is ${RUN_ID}"
           echo 'secured toolchain-id is ${TOOLCHAIN_ID}'
+    - name: get-toolchain-old-way
+      image: ibmcom/pipeline-base-image
+      env:
+        - name: REPOSITORY
+          value: $(inputs.params.repository)
+        - name: TOOLCHAIN_ID
+          value: $(inputs.params.toolchain-id)
+      command: ["/bin/sh", "-c"]
+      args:
+        - |
+          echo "Testing env passing $PASSING_ENV"
+          ibmcloud login -a $API -r $REGION --apikey $API_KEY ;
+          TOKEN=$(ibmcloud iam oauth-tokens --output JSON | jq -r .iam_token)
+          curl -s -X GET -o _toolchain.json -H "Accept: application/json" -H "Authorization: ${TOKEN}" "https://console.cloud.ibm.com/devops/toolchains/$TOOLCHAIN_ID?env_id=ibm:yp:us-south"
+          if jq '.services' _toolchain.json > /dev/null 2>&1; then
+            echo "Found toolchain with id $TOOLCHAIN_ID in region $REGION"
+          else
+            echo "Toolchain with id $TOOLCHAIN_ID in region $REGION not found"
+            exit 1
+          fi
+          cat _toolchain.json
+          cat _toolchain.json | jq -r --arg git_repo "$REPOSITORY" '.services[] | select (.parameters.repo_url==$git_repo) | .parameters.token_url'
     - name: toolchain-object-from-volume
       image: ibmcom/pipeline-base-image
       env:
@@ -103,27 +125,6 @@ spec:
           echo "for MYTOOLCHAIN"
           echo "REPOSITORY is ${REPOSITORY}"
           echo ${MYTOOLCHAIN//$'\\n'}  | jq -r --arg git_repo "$REPOSITORY" '.services[] | select (.parameters.repo_url==$git_repo) | .parameters.token_url'
-    - name: get-toolchain-old-way
-      image: ibmcom/pipeline-base-image
-      env:
-        - name: REPOSITORY
-          value: $(inputs.params.repository)
-        - name: TOOLCHAIN_ID
-          value: $(inputs.params.toolchain-id)
-      command: ["/bin/sh", "-c"]
-      args:
-        - |
-          echo "Testing env passing $PASSING_ENV"
-          ibmcloud login -a $API -r $REGION --apikey $API_KEY ;
-          TOKEN=$(ibmcloud iam oauth-tokens --output JSON | jq -r .iam_token)
-          curl -s -X GET -o _toolchain.json -H "Accept: application/json" -H "Authorization: ${TOKEN}" "https://dev.console.test.cloud.ibm.com/devops/toolchains/$TOOLCHAIN_ID?env_id=ibm:ys1:us-south"
-          if jq '.services' _toolchain.json > /dev/null 2>&1; then
-            echo "Found toolchain with id $TOOLCHAIN_ID in region $REGION"
-          else
-            echo "Toolchain with id $TOOLCHAIN_ID in region $REGION not found"
-            exit 1
-          fi
-          cat _toolchain.json | jq -r --arg git_repo "$REPOSITORY" '.services[] | select (.parameters.repo_url==$git_repo) | .parameters.token_url'
     - name: trigger-another-tekton-pipeline
       image: ibmcom/pipeline-base-image
       env:
@@ -136,9 +137,9 @@ spec:
       command: ["/bin/sh", "-c"]
       args:
         - |
-          ibmcloud login -a $API -r $REGION --apikey $API_KEY ;
-          TOKEN=$(ibmcloud iam oauth-tokens --output JSON | jq -r .iam_token)
-          curl -X POST \
+          # ibmcloud login -a $API -r $REGION --apikey $API_KEY ;
+          # TOKEN=$(ibmcloud iam oauth-tokens --output JSON | jq -r .iam_token)
+          # curl -X POST \
             "https://devops-api.${REGION}.devops.cloud.ibm.com/v1/tekton-pipelines/${ANOTHER_PIPELINE_ID}/runs"\
             -H "Accept: application/json" \
             -H "Content-Type: application/json" \
